apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: 327263453975.dkr.ecr.ap-south-1.amazonaws.com/predictor:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: { path: /health, port: 8080 }
        livenessProbe:
          httpGet: { path: /health, port: 8080 }
