apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predictor-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:327263453975:certificate/123456
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: predictor-svc
            port:
              number: 80
